//C++ is a compiled language.
//When we talk about the portability of c++, we mean the portability of
//its source code which can be compiled on various systems and then run
//on them. The executable generated by the compilation process is not
//portable. It is tied to the underlying hardware / system combination.

//C++ is a statically typed language.
#include <iostream>

int main()
{
    std::cout << "Hello, World\n";
}
